hooks-options:
  # Here is where you can customize all options about the WorldGuard hook.
  world-guard:
    # This toggles the WorldGuard hook.
    use-hook: false
    # Regions inside the list below will allow PTG to perform its magic inside each region.
    region-whitelist:
    - "allowed_zone"
  feudal:
    # If this is enabled, physics to go features will not work within claimed land.
    use-hook: false
  factions:
    # If this is enabled, physics to go features will not work within claimed land.
    use-factions: false
    # If this is enabled, the hook will use Factions UUID over Massive Core.
    factions-uuid: false
  grief-preventation:
    # If this is enabled, physics to go features will not work within claimed land.
    use-grief-preventation: false
  askyblock:
    # If this is enabled, physics to go features will not work on islands.
    use-askyblock: false
  lands:
    # If this is enabled, physics to go features will not work within claimed land.
    use-lands: false
  residence:
    # If this is enabled, physics to go features will not work within residence land.
    use-residence: false
  towny:
    # If this is enabled, physics to go features will not work within town blocks.
    use-towny: false

explosive-options:
  # If this is enabled blocks will not be effected by explosions.
  block-damage: true
  # When blocks are damaged from explosions, should all effected blocks be tossed in different directions?
  block-physics: true
  # When blocks are damaged from explosions, should they be effected by PTG's regeneration effects?
  block-regeneration: true
  # If this is enabled falling blocks will form upon contact.
  block-physics-form: false
  # Here is where you can customize options that effect the block regeneration.
  block-regeneration-options:
    # This option is how fast each block is regenerated in ticks. (Note: 20 ticks equals 1 second.)
    speed: 20
    # This option is how long before the regeneration process takes place in ticks. (Note: 20 ticks equals 1 second.)
    delay: 20
  # Materials inside the list below will be avoided by any regeneration or physic effects involved with explosions.
  effected-material-blacklist:
  - "MOB_SPAWNER:0"
  - "BEDROCK:0"
  # When blocks are damaged from explosions, should the effected blocks drop their relative items?
  block-drops: false
  # If this option is enabled, previously destroyed container and sign contents will be restored to regenerated blocks.
  block-restoration-memory: true
  # Should destroyed containers drop their items?
  # (Note: The items will be restored inside the container if the above option is enabled.)
  container-drops: false
  # The worlds inside the list below will not be effected by any explosive modification made by PTG.
  blacklisted-worlds:
  - "world_the_end"
  # Entity types inside the list bellow will be effected by any explosive modification made by PTG.
  entity-explosion-blacklist:
  - "CREEPER"
  # This tells PTG to regenerate block only if they are below the defined Y-axis below.
  regeneration-height: -1

block-break-options:
  # If this is enabled PTG will listen when a player breaks a block and perform effects.
  block-break-event: false
  # When blocks are damaged by players, should the blocks be regenerated?
  block-regeneration: true
  # Here is where you can customize options that effect the block regeneration.
  block-regeneration-options:
    # This option is how long before the regeneration process takes place in ticks. (Note: 20 ticks equals 1 second.)
    delay: 20
  # Materials inside the list below will be avoided by any regeneration or physics effects involved with block breaking.
  effected-material-blacklist:
  - "OBSIDIAN:0"
  - "BEDROCK:0"
  # When blocks are damaged from players, should the effected blocks drop their relative items?
  block-drops: false
  # If this option is enabled, previously destroyed container and sign contents will be restored to regenerated blocks.
  block-restoration-memory: true
  # Should destroyed containers drop their items?
  # (Note: The items will be restored inside the container if the above option is enabled.)
  container-drops: false
  # The worlds inside the list below will not be effected by any player block damage modified by PTG.
  blacklisted-worlds:
  - "world_the_end"
  # This tells PTG to regenerate block only if they are below the defined Y-axis below.
  regeneration-height: -1

block-place-options:
  # If this is enabled PTG will listen when a player places a block and perform effects.
  block-place-event: false
  # If this is enabled block placing will be cancelled. (Note: This will avoid the 'block-reversion' feature.)
  block-place-cancel: false
  # When blocks are damaged by players, should the blocks be regenerated?
  block-reversion: true
  # Here is where you can customize options that effect the block regeneration.
  block-reversion-options:
    # This option is how long before the regeneration process takes place in ticks. (Note: 20 ticks equals 1 second.)
    delay: 20
  # Materials inside the list below will be avoided by any reversion or physics effects involved with block placing.
  effected-material-blacklist:
  - "OBSIDIAN:0"
  - "BEDROCK:0"
  # The worlds inside the list below will not be effected by any player placement modifications by PTG.
  blacklisted-worlds:
  - "world_the_end"
  # This tells PTG to regenerate block only if they are below the defined Y-axis below.
  # (Note: For block placing blocks will not be 'reverted' unless below/equal to the defined height below.)
  reversion-height: -1