name: PhysicsToGo
version: 1.8.7-B
api-version: 1.13
main: XZot1K.plugins.ptg.PhysicsToGo
author: XZot1K
description: PhysicsToGo is a lightweight physics & environmental regeneration plugin.
softdepend: [WorldGuard, WorldEdit, Factions, MassiveCore, Residence, Towny, Feudal, Kingdoms]
commands:
  ptg:
    default: op
permissions:
  ptg.bypass:
    default: op
    description: Enables the player to bypass all enabled bypassable modules.
    children:
      ptg.bypass.break: true
      ptg.bypass.place: true
  ptg.bypass.break:
    default: op
    description: Enables the player to break blocks without them being regenerated (If the module is enabled).
  ptg.bypass.place:
    default: op
    description: Enables the player to place blocks without them being reverted (If the module is enabled).
  ptg.reload:
    default: op
    description: Enables the player to use the reload command.